name: Auto Redeploy gateway Service

on:
  schedule:
    - cron: "2 * * * *"   # runs every hour (UTC)

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d4g2o9ggjchc73dok190?key=QlTTepiwOoY
